name: "Conventional Pull Request"
description: "Lint PR to enforce only conventional commits make it into the main branch"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  commitlintRulesPath:
    description: "Relative path to commitlint rules file"
    required: false
  commitTitleMatch:
    description: "PRs with a single commit require the PR title and commit message to match"
    required: false
    default: "true"
