name: "Conventional Pull Request"
description: "Lint pull requests with the conventional commit spec, for a clean and conventional commit history"
author: "Matt Bedell <matt@bedell.co>"
branding:
  icon: "git-pull-request"
  color: "green"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  commitlintRulesPath:
    description: "Relative path to commitlint rules file"
    required: false
  commitTitleMatch:
    description: "PRs with a single commit require the PR title and commit message to match"
    required: false
    default: "true"
