#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# if this is the first commit, then it must have a conventional commit message so single commit pull requests always have a proper merge commit message via github
if [[ -z $(git log main..HEAD --oneline) ]]; then
  npx --no-install commitlint --edit "$1"
fi
